server:
  port: 8189
  error:
    include-stacktrace: never

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    enable: true
    cors:
      allowed-origins: true
      printer:
        enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: funscrutFirst
    password: 191220#Destin
    virtual-host: /

logging:
  level:
    springframework:
      cache:
        DEBUG
    org:
      jooq:
        tools:
          LoggerListener: debug

